name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Setup MAUI
      run: sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json
        
    - name: Restore dependencies
      run: cd Soft && dotnet workload restore
      
    - name: Build
      run: cd Soft && dotnet build
      
    - name: Test
      run: cd Soft && dotnet test --no-build --verbosity normal 
