name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: cd Soft && dotnet workload restore
      
    - name: Build
      run: cd Soft && dotnet build -c Release --no-restore
      
    - name: Test
      run: cd Soft && dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
